require('dotenv').config()
const db = require('../db')

const products = [
  // ── TINTURAS — Serie Natural ───────────────────────────────────────────────
  { nombre: '1N Negro', tagline: 'Serie Natural', descripcion: 'Negro intenso con cobertura total de canas. Acabado brillante y uniforme de larga duración.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '3N Castaño Oscuro', tagline: 'Serie Natural', descripcion: 'Castaño oscuro rico y profundo. Cobertura completa con reflejos naturales de larga duración.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '4N Castaño', tagline: 'Serie Natural', descripcion: 'Castaño puro y equilibrado. Ideal para unificar el color y cubrir canas de forma homogénea.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '5N Castaño Claro', tagline: 'Serie Natural', descripcion: 'Castaño claro luminoso con cobertura total. Aporta brillo natural y vitalidad al cabello.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6N Rubio Oscuro', tagline: 'Serie Natural', descripcion: 'Rubio oscuro cálido y natural. Transición perfecta entre el castaño y el rubio.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7N Rubio', tagline: 'Serie Natural', descripcion: 'Rubio natural equilibrado con reflejos dorados suaves. Cobertura total y brillo intenso.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8N Rubio Claro', tagline: 'Serie Natural', descripcion: 'Rubio claro luminoso con acabado brillante. Perfecto para aclarar sin perder calidez.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9N Rubio Muy Claro', tagline: 'Serie Natural', descripcion: 'Rubio muy claro con máxima luminosidad. Ideal para bases claras que buscan mayor claridad.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '10N Rubio Extra Claro', tagline: 'Serie Natural', descripcion: 'Rubio extra claro de alta luminosidad. Efecto aclarante con cobertura uniforme.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Ceniza ───────────────────────────────────────────────
  { nombre: '1,1 Negro Azulado', tagline: 'Serie Ceniza', descripcion: 'Negro con pigmentos azulados fríos para un acabado sofisticado y antibrillo rojizo.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '5,1 Castaño Claro Ceniza', tagline: 'Serie Ceniza', descripcion: 'Castaño claro con matices ceniza fríos que neutralizan tonos anaranjados indeseados.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,1 Rubio Oscuro Ceniza', tagline: 'Serie Ceniza', descripcion: 'Rubio oscuro con pigmentos ceniza para neutralizar reflejos cobrizos. Acabado frío y elegante.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,1 Rubio Ceniza', tagline: 'Serie Ceniza', descripcion: 'Rubio ceniza frío y natural. Neutraliza los tonos cálidos para un acabado plateado sofisticado.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,1 Rubio Claro Ceniza', tagline: 'Serie Ceniza', descripcion: 'Rubio claro con matices ceniza. Perfecto para lograr tonos beige fríos y luminosos.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9,1 Rubio Muy Claro Ceniza', tagline: 'Serie Ceniza', descripcion: 'Rubio muy claro ceniza con efecto plateado. Máxima neutralización de tonos cálidos.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '10,1 Platino', tagline: 'Serie Ceniza', descripcion: 'Platino puro con pigmentos ultra fríos. El tono más claro y sofisticado de la serie ceniza.', precio: 42, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,11 Rubio Oscuro Ceniza Profundo', tagline: 'Serie Ceniza', descripcion: 'Ceniza profunda intensificada para mayor neutralización de tonos cobrizos en bases oscuras.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,11 Rubio Claro Ceniza Profundo', tagline: 'Serie Ceniza', descripcion: 'Ceniza profunda en tono rubio claro. Acabado ultra frío con máxima cobertura de reflejos dorados.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '12,1 Aclarante Ceniza', tagline: 'Serie Ceniza', descripcion: 'Aclarante con pigmentos ceniza. Eleva el tono base neutralizando reflejos cálidos simultáneamente.', precio: 44, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Chocolate ────────────────────────────────────────────
  { nombre: '5,7 Chocolate Oscuro', tagline: 'Serie Chocolate', descripcion: 'Chocolate oscuro intenso con reflejos cálidos de cacao. Profundidad y luminosidad en un solo tono.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,7 Chocolate', tagline: 'Serie Chocolate', descripcion: 'Chocolate clásico con reflejos caramelados. Tono irresistible que aporta calor y vida al cabello.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,7 Rubio Chocolate', tagline: 'Serie Chocolate', descripcion: 'Rubio con reflejos chocolate suaves y cálidos. La combinación perfecta entre luminosidad y calidez.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Tabaco ───────────────────────────────────────────────
  { nombre: '6,73 Tabaco Oscuro', tagline: 'Serie Tabaco', descripcion: 'Tabaco oscuro dorado con reflejos avellanados. Tono sofisticado y tendencia que combina ceniza y dorado.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,73 Tabaco Mediano', tagline: 'Serie Tabaco', descripcion: 'Rubio tabaco equilibrado con matices dorados y ceniza. Tono moderno de gran versatilidad.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,73 Tabaco Claro', tagline: 'Serie Tabaco', descripcion: 'Tabaco claro luminoso con acabado arena dorado. Ideal para looks naturales con dimensión.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Café ─────────────────────────────────────────────────
  { nombre: '7,14 Rubio Ceniza Café', tagline: 'Serie Café', descripcion: 'Rubio con matices ceniza y café para un tono grisáceo frío con calidez sutil. Muy tendencia.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Marrón Profundo ──────────────────────────────────────
  { nombre: '5M Castaño Claro Marrón Profundo', tagline: 'Serie Marrón Profundo', descripcion: 'Castaño claro con intensidad marrón profunda. Cobertura total y acabado sedoso de larga duración.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6M Rubio Oscuro Marrón Profundo', tagline: 'Serie Marrón Profundo', descripcion: 'Rubio oscuro con intensidad marrón enriquecida. Tono cálido con máxima profundidad de color.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7M Rubio Marrón Profundo', tagline: 'Serie Marrón Profundo', descripcion: 'Rubio con reflejos marrón profundo. Aporta dimensión y profundidad a tonos medios y claros.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Malva ────────────────────────────────────────────────
  { nombre: '7,2 Rubio Malva', tagline: 'Serie Malva', descripcion: 'Rubio con matices malva fríos y sofisticados. Neutraliza reflejos amarillos con un toque rosado elegante.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,2 Rubio Claro Malva', tagline: 'Serie Malva', descripcion: 'Rubio claro con pigmentos malva que aportan un tono beige rosado muy luminoso y de tendencia.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9,2 Rubio Muy Claro Malva', tagline: 'Serie Malva', descripcion: 'Rubio muy claro con suaves reflejos malva. Perfecto para bases claras que buscan un tono perlado.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,32 Rubio Dorado Malva', tagline: 'Serie Malva', descripcion: 'Combinación única de dorado y malva en un rubio de calidez equilibrada con toque rosado.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,32 Rubio Claro Dorado Malva', tagline: 'Serie Malva', descripcion: 'Rubio claro con reflejos dorado-malva. Tono suave y femenino con luminosidad especial.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '1002 Muy Aclarante Malva', tagline: 'Serie Malva', descripcion: 'Aclarante con pigmentos malva para máxima elevación de tono con acabado rosado perlado.', precio: 44, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Dorada ───────────────────────────────────────────────
  { nombre: '6,3 Rubio Oscuro Dorado', tagline: 'Serie Dorada', descripcion: 'Rubio oscuro con reflejos dorados intensos. Calor y luminosidad mediterránea en cada hebra.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,3 Rubio Dorado', tagline: 'Serie Dorada', descripcion: 'Rubio dorado clásico con brillos solares. Tono cálido y atemporal de máxima luminosidad.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,3 Rubio Claro Dorado', tagline: 'Serie Dorada', descripcion: 'Rubio claro dorado luminoso. Perfecto para evocar los tonos naturales del cabello bajo el sol.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9,3 Rubio Muy Claro Dorado', tagline: 'Serie Dorada', descripcion: 'Rubio muy claro con dorado brillante. Máxima luminosidad con calidez solar controlada.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,31 Rubio Dorado Beige', tagline: 'Serie Dorada', descripcion: 'Rubio dorado con matices beige naturales. Tono versátil que combina calor y neutralidad.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,31 Rubio Claro Dorado Beige', tagline: 'Serie Dorada', descripcion: 'Rubio claro beige dorado con acabado natural. Ideal para resultados frescos y luminosos.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9,31 Rubio Muy Claro Dorado Beige', tagline: 'Serie Dorada', descripcion: 'Rubio muy claro con suave dorado beige. El tono más luminoso y natural de la serie.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9,13 Rubio Muy Claro Ceniza Beige', tagline: 'Serie Dorada', descripcion: 'Rubio muy claro con fusión de ceniza y beige para un acabado perlado natural y sofisticado.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Cobriza ──────────────────────────────────────────────
  { nombre: '8,43 Rubio Claro Cobrizo Dorado', tagline: 'Serie Cobriza', descripcion: 'Rubio claro con reflejos cobrizos y dorados. Combinación cálida de gran impacto visual.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,4 Rubio Oscuro Cobrizo', tagline: 'Serie Cobriza', descripcion: 'Rubio oscuro con intensa carga cobriza. Aporta fuego y personalidad al cabello oscuro.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,4 Rubio Cobrizo', tagline: 'Serie Cobriza', descripcion: 'Rubio con reflejos cobrizos vibrantes. Tono encendido y sensual de alto impacto.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,34 Rubio Claro Dorado Cobrizo', tagline: 'Serie Cobriza', descripcion: 'Rubio claro con matices dorado-cobrizos equilibrados. Calor y luminosidad en perfecta armonía.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Caoba / Roja ─────────────────────────────────────────
  { nombre: '5,6 Caoba', tagline: 'Serie Caoba', descripcion: 'Caoba clásico con intensidad rojiza profunda. Tono apasionado y de máxima cobertura.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,6 Caoba Claro', tagline: 'Serie Caoba', descripcion: 'Caoba claro luminoso con reflejos rojizos elegantes. Vibrante y de larga duración.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,22 Rubio Oscuro Violeta', tagline: 'Serie Caoba', descripcion: 'Rubio oscuro con pigmentos violeta intensos. Tono frío y sofisticado con acabado joya.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '5,66 Castaño Claro Rojizo Profundo', tagline: 'Serie Roja Profunda', descripcion: 'Castaño claro con carga rojiza profunda intensificada. Rojo rico y de máximo impacto.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,66 Rubio Oscuro Rojo Profundo', tagline: 'Serie Roja Profunda', descripcion: 'Rubio oscuro con doble pigmento rojo para una intensidad vibrante y duradera.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,66 Rubio Rojo Profundo', tagline: 'Serie Roja Profunda', descripcion: 'Rubio con intensidad rojiza profunda. Encendido y apasionado con brillo espejo.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '5,64 Castaño Claro Rojo Cobrizo', tagline: 'Serie Roja Profunda', descripcion: 'Castaño claro con fusión de rojo y cobre. Tono vibrante con destellos cobrizo-rojizos únicos.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,64 Rubio Oscuro Rojo Cobrizo', tagline: 'Serie Roja Profunda', descripcion: 'Rubio oscuro con mezcla de rojo y cobre de gran calidez. Tono moderno y muy favorecedor.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,64 Rubio Rojo Cobrizo', tagline: 'Serie Roja Profunda', descripcion: 'Rubio luminoso con reflejos rojo-cobrizos. Caliente, encendido y de tendencia en cada temporada.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Profunda ─────────────────────────────────────────────
  { nombre: '5,0 Castaño Claro Profundo', tagline: 'Serie Profunda', descripcion: 'Castaño claro con doble pigmento base para máxima profundidad de color y cobertura total.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '6,0 Rubio Oscuro Profundo', tagline: 'Serie Profunda', descripcion: 'Rubio oscuro con carga pigmentaria extra para tonos más intensos y de mayor duración.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '7,0 Rubio Profundo', tagline: 'Serie Profunda', descripcion: 'Rubio con pigmentos base reforzados. Mayor cobertura y rendimiento en bases resistentes.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,0 Rubio Claro Profundo', tagline: 'Serie Profunda', descripcion: 'Rubio claro con intensidad base reforzada. Ideal para cubrir canas resistentes con uniformidad.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9,0 Rubio Muy Claro Profundo', tagline: 'Serie Profunda', descripcion: 'Rubio muy claro con mayor intensidad pigmentaria para resultados más vibrantes y duraderos.', precio: 38, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Perlada ──────────────────────────────────────────────
  { nombre: '9,12 Gris Perla', tagline: 'Serie Perlada', descripcion: 'Tono gris perla de alta sofisticación. Fusiona ceniza y malva para un efecto perlado luminoso.', precio: 42, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8,21 Rubio Claro Glasé Ceniza', tagline: 'Serie Perlada', descripcion: 'Rubio claro glasé con matices ceniza. Efecto perlado frío de gran luminosidad y refinamiento.', precio: 42, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9,21 Rubio Muy Claro Glasé Ceniza', tagline: 'Serie Perlada', descripcion: 'Rubio muy claro glasé con shimmer ceniza. El tono más exclusivo para cabellos platinados.', precio: 42, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '10,21 Rubio Extraclaro Glasé Ceniza', tagline: 'Serie Perlada', descripcion: 'Extraclaro con efecto glasé ceniza perlado. Máxima luminosidad fría para un look platino premium.', precio: 44, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Serie Ceniza Malva ─────────────────────────────────────────
  { nombre: '7CM Rubio Ceniza Malva', tagline: 'Serie Ceniza Malva', descripcion: 'Rubio con mezcla exclusiva de ceniza y malva. Tono frío rosado muy de moda y favorecedor.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '8CM Rubio Claro Ceniza Malva', tagline: 'Serie Ceniza Malva', descripcion: 'Rubio claro ceniza malva luminoso. Perfecto para lograr el efecto smoky rose tan tendencia.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: '9CM Rubio Muy Claro Ceniza Malva', tagline: 'Serie Ceniza Malva', descripcion: 'Rubio muy claro con matices ceniza-malva. El tono más delicado y luminoso de la serie CM.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── TINTURAS — Correctores & Pasteles ─────────────────────────────────────
  { nombre: '0,11 Corrector Azul', tagline: 'Correctores & Pasteles', descripcion: 'Corrector azul concentrado para neutralizar reflejos anaranjados y rojizos en procesos de decoloración.', precio: 35, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: 'AP Azulino Pastel', tagline: 'Correctores & Pasteles', descripcion: 'Tono pastel azulado de fantasía sobre bases muy claras. Delicado efecto celeste de corta duración.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: 'RP Rosa Pastel', tagline: 'Correctores & Pasteles', descripcion: 'Rosa pastel suave y romántico. Efecto fantasía sobre cabello decolorado para un look muy femenino.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: 'LP Lavanda Pastel', tagline: 'Correctores & Pasteles', descripcion: 'Lavanda pastel sutil y sofisticado. Tono fantasía de gran tendencia para bases extra claras.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  { nombre: 'SP Salmón Pastel', tagline: 'Correctores & Pasteles', descripcion: 'Salmón pastel cálido y delicado. Efecto melocotón suave ideal para looks románticos y frescos.', precio: 40, linea: 'Tinturas', tipo_cabello: ['Teñido'] },
  // ── ÁCIDO ─────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Extra Ácido pH 3,5 300ml', tagline: 'Extra Ácido pH 3,5', descripcion: 'Shampoo ultra ácido pH 3,5 que sella la cutícula, fija el color y prolonga la duración de cualquier tratamiento químico.', precio: 48, linea: 'Ácido', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Acondicionador Extra Ácido pH 3,5 300ml', tagline: 'Extra Ácido pH 3,5', descripcion: 'Acondicionador de pH 3,5 que cierra la cutícula y aporta brillo espejo tras coloraciones, alisados y keratinas.', precio: 48, linea: 'Ácido', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Máscara Extra Ácida pH 3,5 250ml', tagline: 'Extra Ácido pH 3,5', descripcion: 'Máscara selladora de pH 3,5 para tratamiento post químico. Hidrata en profundidad y sella la cutícula para mayor duración del color.', precio: 60, linea: 'Ácido', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Máscara Extra Ácida pH 3,5 1000ml', tagline: 'Extra Ácido pH 3,5', descripcion: 'Máscara extra ácida en formato profesional 1L. Sellado intensivo de cutícula para uso en salón con resultados de brillo espejo.', precio: 105, badge: 'Profesional', linea: 'Ácido', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Pack 24 Baño Extra Ácido x20ml', tagline: 'Extra Ácido pH 3,5', descripcion: 'Pack de 24 baños individuales de 20ml de tratamiento extra ácido. Ideal para mantenimiento post alisado o coloración en casa.', precio: 88, badge: 'Pack', linea: 'Ácido', tipo_cabello: ['Teñido', 'Dañado'] },
  // ── ALMENDRAS ─────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Almendras 300ml', tagline: 'Almendras', descripcion: 'Shampoo nutritivo con aceite de almendras dulces que nutre, suaviza y aporta brillo natural al cabello seco y sin vida.', precio: 48, linea: 'Almendras', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Acondicionador Almendras 300ml', tagline: 'Almendras', descripcion: 'Acondicionador con manteca de almendras que desenreda, nutre y aporta sedosidad al cabello reseco y quebradizo.', precio: 48, linea: 'Almendras', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Máscara Almendras 250ml', tagline: 'Almendras', descripcion: 'Máscara nutritiva con aceite de almendras y vitamina E. Recupera la suavidad y el brillo del cabello dañado.', precio: 60, linea: 'Almendras', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Máscara Brillo + Hidratación Almendras 1000ml', tagline: 'Almendras', descripcion: 'Máscara de almendras en formato 1L con doble acción: brillo intenso e hidratación profunda.', precio: 108, badge: 'Profesional', linea: 'Almendras', tipo_cabello: ['Seco', 'Dañado'] },
  // ── COCO ──────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Coco Cabellos Secos 300ml', tagline: 'Coco', descripcion: 'Shampoo con aceite de coco virgen para cabellos extra secos. Hidrata desde la primera aplicación y aporta suavidad duradera.', precio: 48, linea: 'Coco', tipo_cabello: ['Seco'] },
  { nombre: 'Acondicionador Coco Cabellos Secos 300ml', tagline: 'Coco', descripcion: 'Acondicionador de coco para cabello muy seco. Nutre, hidrata y facilita el peinado sin dejar residuo graso.', precio: 48, linea: 'Coco', tipo_cabello: ['Seco'] },
  { nombre: 'Máscara de Coco 250ml', tagline: 'Coco', descripcion: 'Máscara intensiva con aceite de coco y proteínas vegetales. Restaura la hidratación del cabello seco en una sola aplicación.', precio: 60, linea: 'Coco', tipo_cabello: ['Seco'] },
  { nombre: 'Máscara de Coco Cabellos Secos 1000ml', tagline: 'Coco', descripcion: 'Máscara de coco en formato profesional 1L. Hidratación profunda y duradera para cabellos muy secos y deshidratados.', precio: 105, badge: 'Profesional', linea: 'Coco', tipo_cabello: ['Seco'] },
  // ── SEMI DI LINO ──────────────────────────────────────────────────────────
  { nombre: 'Shampoo Semi Di Lino 300ml', tagline: 'Semi Di Lino', descripcion: 'Shampoo con aceite de semillas de lino que hidrata, suaviza y aporta flexibilidad al cabello seco y quebradizo.', precio: 52, linea: 'Semi Di Lino', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Acondicionador Semi Di Lino 300ml', tagline: 'Semi Di Lino', descripcion: 'Acondicionador de lino que nutre y desenreda sin pesar el cabello. Aporta brillo y suavidad sedosa.', precio: 52, linea: 'Semi Di Lino', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Máscara Semi Di Lino 250ml', tagline: 'Semi Di Lino', descripcion: 'Máscara capilar de aceite de lino con efecto reparador y suavizante. Ideal para cabellos secos, finos o con puntas abiertas.', precio: 65, linea: 'Semi Di Lino', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Máscara Capilar Semi Di Lino 1000ml', tagline: 'Semi Di Lino', descripcion: 'Máscara de lino en formato 1L para uso profesional. Nutrición, hidratación y suavidad extrema.', precio: 112, badge: 'Profesional', linea: 'Semi Di Lino', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Ampollas Semi Di Lino x12 (15ml c/u)', tagline: 'Semi Di Lino', descripcion: 'Pack de 12 ampollas de aceite de lino puro. Tratamiento concentrado que repara la fibra capilar desde el interior.', precio: 98, badge: 'Pack', linea: 'Semi Di Lino', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  // ── BTX ───────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Botox Capilar 300ml', tagline: 'BTX Post Alisado c/Hialurónico', descripcion: 'Shampoo específico para cabello post alisado. Con ácido hialurónico que hidrata y prolonga la duración del tratamiento BTX.', precio: 72, linea: 'BTX', tipo_cabello: ['Dañado', 'Seco'] },
  { nombre: 'Crema de Peinar Botox 250ml', tagline: 'BTX Post Alisado c/Hialurónico', descripcion: 'Crema sin enjuague con tecnología botox y hialurónico. Alisa, suaviza y protege el cabello post alisado.', precio: 78, linea: 'BTX', tipo_cabello: ['Dañado', 'Seco', 'Grueso'] },
  { nombre: 'Ampollas BTX Post Alisado x12 (15ml c/u)', tagline: 'BTX Post Alisado c/Hialurónico', descripcion: 'Pack de 12 ampollas concentradas de botox capilar con hialurónico. Tratamiento intensivo que rellena la porosidad y sella el color del alisado.', precio: 110, badge: 'Premium', linea: 'BTX', tipo_cabello: ['Dañado', 'Seco'] },
  { nombre: 'Máscara Botox Capilar 250ml', tagline: 'BTX Post Alisado c/Hialurónico', descripcion: 'Máscara de botox capilar con hialurónico en formato 250ml. Nutrición profunda, suavidad extrema y efecto liso duradero.', precio: 85, linea: 'BTX', tipo_cabello: ['Dañado', 'Seco', 'Grueso'] },
  { nombre: 'Máscara Botox Capilar 1000ml', tagline: 'BTX Post Alisado c/Hialurónico', descripcion: 'Máscara de botox capilar con hialurónico en formato profesional 1L. Ideal para uso en salón.', precio: 145, badge: 'Profesional', linea: 'BTX', tipo_cabello: ['Dañado', 'Seco', 'Grueso'] },
  // ── ESLOM KERATINA ────────────────────────────────────────────────────────
  { nombre: 'Shampoo Eslom Keratina 300ml', tagline: 'Eslom Keratina', descripcion: 'Shampoo con complejo de keratina hidrolizada que limpia suavemente mientras reconstruye la fibra capilar.', precio: 55, linea: 'Eslom Keratina', tipo_cabello: ['Dañado', 'Rizado', 'Grueso'] },
  { nombre: 'Acondicionador Eslom Keratina 300ml', tagline: 'Eslom Keratina', descripcion: 'Acondicionador keratínico que hidrata, suaviza y aporta efecto liso natural. Prolonga la duración de los tratamientos alisadores.', precio: 55, linea: 'Eslom Keratina', tipo_cabello: ['Dañado', 'Rizado', 'Grueso'] },
  { nombre: 'Máscara Eslom Keratina 250ml', tagline: 'Eslom Keratina', descripcion: 'Máscara de reconstrucción keratínica con tecnología Eslom. Rellena la porosidad, aporta brillo espejo y reduce el frizz.', precio: 68, linea: 'Eslom Keratina', tipo_cabello: ['Dañado', 'Rizado', 'Grueso'] },
  { nombre: 'Máscara Capilar Eslom Keratina 1000ml', tagline: 'Eslom Keratina', descripcion: 'Máscara keratínica en formato profesional 1L. Reconstrucción intensiva para uso en salón.', precio: 118, badge: 'Profesional', linea: 'Eslom Keratina', tipo_cabello: ['Dañado', 'Rizado', 'Grueso'] },
  { nombre: 'Nutri-Care Eslom Reparación Total Amp. x12 (15ml c/u)', tagline: 'Eslom Keratina', descripcion: 'Pack de 12 ampollas de reparación total con keratina y nutrientes activos. Regenera la fibra desde el córtex hacia la cutícula.', precio: 115, badge: 'Premium', linea: 'Eslom Keratina', tipo_cabello: ['Dañado', 'Seco', 'Rizado'] },
  { nombre: 'Cauterizado Eslom Keratínico Amp. x12 (15ml c/u)', tagline: 'Eslom Keratina', descripcion: 'Ampollas de cauterizado keratínico de alta concentración. Sella puntas abiertas, reconstruye zonas dañadas y aporta un acabado liso y brillante.', precio: 120, badge: 'Premium', linea: 'Eslom Keratina', tipo_cabello: ['Dañado', 'Seco', 'Grueso'] },
  // ── OXIDANTES ─────────────────────────────────────────────────────────────
  { nombre: 'Revelador 5 Vol Crema 1000ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Revelador en crema de 5 volúmenes. Ideal para tonificaciones suaves, aclarado mínimo y mezclas con tintes de baja intensidad.', precio: 55, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 10 Vol Crema 1000ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 10 volúmenes. Para deposición de color sin aclarado, ideal para cubrir canas y refrescar el color base.', precio: 55, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 20 Vol Crema 1000ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 20 volúmenes. El más versátil: aclarado moderado, cobertura total de canas y color estándar.', precio: 55, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 30 Vol Crema 1000ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 30 volúmenes. Aclarado significativo para lograr tonos rubios medios y claros.', precio: 55, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 40 Vol Crema 1000ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 40 volúmenes. Para máximo levantamiento de color, decoloración y aclarados extremos en un solo paso.', precio: 55, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 60 Vol 1000ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante profesional de 60 volúmenes. Uso exclusivo en salón para aclarados intensivos y preparación de bases muy oscuras.', precio: 62, badge: 'Profesional', linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Revelador 5 Vol Crema 90ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Revelador en crema de 5 volúmenes en formato individual 90ml. Para tonificaciones y retoques puntuales.', precio: 18, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 10 Vol Crema 90ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 10 volúmenes en formato 90ml. Ideal para retoques de raíz o mezclas con una sola aplicación de tinte.', precio: 18, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 20 Vol Crema 90ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 20 volúmenes en formato 90ml. El más popular para uso individual con tinte de cualquier línea.', precio: 18, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 30 Vol Crema 90ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 30 volúmenes en formato 90ml. Para levantamiento y color en un solo paso.', precio: 18, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  { nombre: 'Oxidante 40 Vol Crema 90ml', tagline: 'Oxidantes Tonaleg', descripcion: 'Oxidante en crema de 40 volúmenes en formato 90ml. Máximo levantamiento en pequeñas porciones para mechas o aclarados puntuales.', precio: 18, linea: 'Oxidantes', tipo_cabello: ['Teñido'] },
  // ── CURLY ─────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Curly 500ml', tagline: 'Curly', descripcion: 'Shampoo sin sulfatos especialmente formulado para cabellos rizados y ondulados. Limpia suavemente respetando el patrón del rizo.', precio: 65, linea: 'Curly', tipo_cabello: ['Rizado'] },
  { nombre: 'Máscara Curly 500ml', tagline: 'Curly', descripcion: 'Máscara hidratante en formato 500ml para rizos bien definidos. Nutre en profundidad, reduce el frizz y potencia la elasticidad natural de cada rizo.', precio: 75, linea: 'Curly', tipo_cabello: ['Rizado', 'Seco'] },
  { nombre: 'Activador de Rizos Curly 250ml', tagline: 'Curly', descripcion: 'Activador sin enjuague que define, hidrata y potencia los rizos naturales. Aporta rebote, brillo y control del frizz.', precio: 52, linea: 'Curly', tipo_cabello: ['Rizado'] },
  { nombre: 'Máscara Curly 250ml', tagline: 'Curly', descripcion: 'Máscara hidratante para rizos en formato 250ml. Ideal para uso diario o como tratamiento semanal.', precio: 48, linea: 'Curly', tipo_cabello: ['Rizado', 'Seco'] },
  { nombre: 'Crema para Peinar Curly 250ml', tagline: 'Curly', descripcion: 'Crema de peinado sin enjuague para rizos definidos y libres de frizz. Fija el rizo de forma flexible y mantiene la hidratación.', precio: 52, linea: 'Curly', tipo_cabello: ['Rizado'] },
  // ── BLONDE ────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Blonde 500ml', tagline: 'Blonde', descripcion: 'Shampoo matizador para cabellos rubios, decolorados y con mechas. Neutraliza los tonos amarillos y anaranjados aportando luminosidad.', precio: 68, linea: 'Blonde', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Máscara Blonde 500ml', tagline: 'Blonde', descripcion: 'Máscara matizadora en formato 500ml para rubios y decolorados. Hidratación profunda con pigmentos violetas que eliminan los reflejos amarillos.', precio: 78, linea: 'Blonde', tipo_cabello: ['Teñido', 'Dañado', 'Seco'] },
  { nombre: 'Protector Termal Blonde 200ml', tagline: 'Blonde', descripcion: 'Protector térmico sin enjuague especial para cabellos rubios y decolorados. Escuda la fibra del calor mientras mantiene el tono frío y el brillo.', precio: 55, linea: 'Blonde', tipo_cabello: ['Teñido', 'Dañado', 'Fino'] },
  { nombre: 'Máscara Blonde 250ml', tagline: 'Blonde', descripcion: 'Máscara matizadora en formato 250ml. Ideal para mantenimiento semanal del tono rubio.', precio: 52, linea: 'Blonde', tipo_cabello: ['Teñido', 'Dañado', 'Seco'] },
  { nombre: 'Sérum Oil Blonde 60ml', tagline: 'Blonde', descripcion: 'Aceite sérum ultra liviano para cabellos rubios y decolorados. Aporta brillo espejo, nutrición sin peso y protección ante el daño del color.', precio: 62, linea: 'Blonde', tipo_cabello: ['Teñido', 'Dañado', 'Fino'] },
  // ── BIOTINA ───────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Post Color con Biotina 300ml', tagline: 'Biotina', descripcion: 'Shampoo post color con biotina que limpia suavemente preservando la intensidad del tinte. Fortalece la fibra capilar.', precio: 50, linea: 'Biotina', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Acondicionador Post Color con Biotina 300ml', tagline: 'Biotina', descripcion: 'Acondicionador con biotina para cabello teñido. Sella la cutícula, aporta suavidad y potencia el brillo del color recién aplicado.', precio: 50, linea: 'Biotina', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Máscara Capilar Post Color con Biotina 250ml', tagline: 'Biotina', descripcion: 'Máscara post color con biotina en formato 250ml. Reconstruye la fibra dañada por el proceso de coloración.', precio: 62, linea: 'Biotina', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Máscara Capilar Post Color con Biotina 1000ml', tagline: 'Biotina', descripcion: 'Máscara post color con biotina en formato profesional 1kg. Nutrición intensa y fijación del color para uso en salón.', precio: 110, badge: 'Profesional', linea: 'Biotina', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Crema de Peinar Post Color con Biotina 250ml', tagline: 'Biotina', descripcion: 'Crema sin enjuague con biotina para cabellos teñidos. Facilita el peinado y protege el color del daño térmico y ambiental.', precio: 55, linea: 'Biotina', tipo_cabello: ['Teñido', 'Dañado', 'Fino'] },
  // ── ARGÁN ─────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Shock Argán 300ml', tagline: 'Argán', descripcion: 'Shampoo con aceite de argán marroquí que limpia y nutre simultáneamente. Aporta hidratación, brillo y suavidad.', precio: 50, linea: 'Argán', tipo_cabello: ['Seco', 'Dañado', 'Grueso'] },
  { nombre: 'Acondicionador Shock Argán 300ml', tagline: 'Argán', descripcion: 'Acondicionador con aceite de argán que desenreda, suaviza y aporta brillo intenso. Reduce el frizz de forma duradera.', precio: 50, linea: 'Argán', tipo_cabello: ['Seco', 'Dañado', 'Grueso'] },
  { nombre: 'Máscara Shock Argán 250ml', tagline: 'Argán', descripcion: 'Máscara de tratamiento con argán puro en formato 250ml. Recupera la suavidad y el brillo del cabello dañado.', precio: 62, linea: 'Argán', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Máscara Shock Argán 1000ml', tagline: 'Argán', descripcion: 'Máscara de argán en formato profesional 1L. Nutrición e hidratación intensiva para uso en salón.', precio: 112, badge: 'Profesional', linea: 'Argán', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Crema de Peinar Shock Argán 250ml', tagline: 'Argán', descripcion: 'Crema sin enjuague con aceite de argán que facilita el peinado y aporta suavidad y brillo sin dejar residuo.', precio: 55, linea: 'Argán', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Brillo Instantáneo Argán Shine Mist', tagline: 'Argán', descripcion: 'Spray de brillo instantáneo con aceite de argán. Aporta un acabado espejo, suavidad y protección ligera ante el calor y el frizz.', precio: 58, linea: 'Argán', tipo_cabello: ['Seco', 'Dañado', 'Fino', 'Grueso'] },
  { nombre: 'Ampollas Argán Tratamiento Restaurador x12 (15ml c/u)', tagline: 'Argán', descripcion: 'Pack de 12 ampollas de aceite de argán puro para restauración intensiva. Repara la fibra capilar desde el interior.', precio: 102, badge: 'Pack', linea: 'Argán', tipo_cabello: ['Seco', 'Dañado'] },
  // ── BACHA ─────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo pH 3,5 c/Teñidos 5000ml', tagline: 'Bacha', descripcion: 'Shampoo de pH 3,5 en formato profesional 5L para cabellos teñidos. Sella la cutícula, fija el color y prolonga la duración de cualquier tratamiento químico.', precio: 220, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Crema Enjuague pH 3,5 Extra Ácida 5000ml', tagline: 'Bacha', descripcion: 'Crema enjuague extra ácida pH 3,5 en formato 5L. Cierra la cutícula y aporta brillo espejo tras coloraciones, alisados y keratinas.', precio: 220, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Shampoo Neutro 5000ml', tagline: 'Bacha', descripcion: 'Shampoo neutro de uso profesional en formato 5L. Limpieza suave y equilibrada apta para todo tipo de cabello.', precio: 195, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Seco', 'Graso', 'Fino', 'Grueso'] },
  { nombre: 'Crema Enjuague Desenredante 5000ml', tagline: 'Bacha', descripcion: 'Crema enjuague desenredante en formato profesional 5L. Suaviza, desenreda y aporta manejabilidad a todo tipo de cabello.', precio: 210, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Seco', 'Rizado', 'Grueso'] },
  { nombre: 'Shampoo Semi Di Lino 5000ml', tagline: 'Bacha', descripcion: 'Shampoo con aceite de semillas de lino en formato profesional 5L. Hidrata, suaviza y aporta flexibilidad al cabello seco y quebradizo.', precio: 215, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Shampoo Brillo c/Aceite de Almendras 5000ml', tagline: 'Bacha', descripcion: 'Shampoo nutritivo con aceite de almendras en formato 5L. Limpia suavemente aportando brillo intenso y suavidad duradera.', precio: 215, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Crema Enjuague de Coco p/Secas 5000ml', tagline: 'Bacha', descripcion: 'Crema enjuague con aceite de coco en formato profesional 5L para cabellos muy secos. Hidratación profunda y suavidad extrema.', precio: 210, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Seco'] },
  { nombre: 'Shampoo Eslom Hidrat./Keratina 5000ml', tagline: 'Bacha', descripcion: 'Shampoo keratínico con complejo hidratante Eslom en formato 5L. Limpia suavemente mientras reconstruye la fibra capilar.', precio: 225, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Dañado', 'Rizado', 'Grueso'] },
  { nombre: 'Acondicionador Eslom Hidrat./Keratina 5000ml', tagline: 'Bacha', descripcion: 'Acondicionador keratínico Eslom en formato profesional 5L. Hidrata, suaviza y prolonga la duración de los tratamientos alisadores.', precio: 225, badge: 'Profesional', linea: 'Bacha', tipo_cabello: ['Dañado', 'Rizado', 'Grueso'] },
  // ── SCOTLAND ──────────────────────────────────────────────────────────────
  { nombre: 'Pomada de Barba Brillante 70ml', tagline: 'Scotland', descripcion: 'Pomada para barba con acabado brillante. Fija, moldea y acondiciona la barba aportando brillo y suavidad durante todo el día.', precio: 0, linea: 'Scotland', tipo_cabello: ['Barba'] },
  { nombre: 'Pomada de Barba Mate 70ml', tagline: 'Scotland', descripcion: 'Pomada para barba con acabado mate natural. Fija y define la barba sin brillos, con una textura manejable y de larga duración.', precio: 0, linea: 'Scotland', tipo_cabello: ['Barba'] },
  { nombre: 'Aceite de Barba Classic 30ml', tagline: 'Scotland', descripcion: 'Aceite de barba clásico en formato 30ml. Hidrata, suaviza y acondiciona la barba y la piel subyacente.', precio: 0, linea: 'Scotland', tipo_cabello: ['Barba'] },
  { nombre: 'Aceite de Barba Mint 30ml', tagline: 'Scotland', descripcion: 'Aceite de barba con fragancia a menta en formato 30ml. Refresca, hidrata y acondiciona la barba.', precio: 0, linea: 'Scotland', tipo_cabello: ['Barba'] },
  { nombre: 'Aceite de Barba Lemon Green 30ml', tagline: 'Scotland', descripcion: 'Aceite de barba con fragancia cítrica limón verde en formato 30ml. Hidrata y suaviza la barba con aroma fresco.', precio: 0, linea: 'Scotland', tipo_cabello: ['Barba'] },
  { nombre: 'Shampoo de Barba 250ml', tagline: 'Scotland', descripcion: 'Shampoo especial para barba en formato 250ml. Limpia en profundidad sin resecar, dejando la barba suave y manejable.', precio: 0, linea: 'Scotland', tipo_cabello: ['Barba'] },
  { nombre: 'Texturizador Polvo Styling 10g', tagline: 'Scotland', descripcion: 'Polvo texturizador para barba y cabello en formato 10g. Aporta volumen, textura y fijación mate.', precio: 0, linea: 'Scotland', tipo_cabello: ['Barba'] },
  // ── COLOR ─────────────────────────────────────────────────────────────────
  { nombre: 'Tonal Canas Mordiente x12 10ml', tagline: 'Color', descripcion: 'Pack de 12 ampollas de 10ml para cubrir canas con mordiente. Rinde 2 aplicaciones por ampolla. Fórmula nueva.', precio: 0, badge: 'Nuevo', linea: 'Color', tipo_cabello: ['Teñido'] },
  { nombre: 'Loción Quitamanchas Tonaleg 250ml', tagline: 'Color', descripcion: 'Loción quitamanchas profesional en formato 250ml. Elimina rápidamente los residuos de tintura sobre la piel.', precio: 0, linea: 'Color', tipo_cabello: ['Teñido'] },
  { nombre: 'Polvo Decolorante Blue Classic 690g', tagline: 'Color', descripcion: 'Polvo decolorante azul clásico en formato 690g. Alta potencia decolorante con fórmula de acción uniforme.', precio: 0, linea: 'Color', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Polvo Decolorante Super Blanc Premium 500g', tagline: 'Color', descripcion: 'Polvo decolorante premium Super Blanc en formato 500g. Fórmula de alta performance para decoloraciones extremas.', precio: 0, badge: 'Premium', linea: 'Color', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Polvo Decolorante Super Mentolado 690g', tagline: 'Color', descripcion: 'Polvo decolorante mentolado en formato 690g. Reduce la sensación de ardor durante el proceso con efecto refrescante.', precio: 0, linea: 'Color', tipo_cabello: ['Teñido', 'Dañado'] },
  // ── SHAMPOO Y ENJUAGUE ────────────────────────────────────────────────────
  { nombre: 'Shampoo Neutro 300ml', tagline: 'Shampoo y Enjuague', descripcion: 'Shampoo neutro Tonaleg en formato 300ml. Limpieza suave y equilibrada apta para todo tipo de cabello y uso frecuente.', precio: 0, linea: 'Shampoo y Enjuague', tipo_cabello: ['Seco', 'Graso', 'Fino', 'Grueso'] },
  // ── TERMINACIÓN ───────────────────────────────────────────────────────────
  { nombre: 'Cera de Brillo 70g', tagline: 'Terminación', descripcion: 'Cera de brillo en formato 70g. Moldea, define y aporta brillo intenso al cabello con una fijación flexible.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Fino', 'Grueso'] },
  { nombre: 'Sérum Oil 30ml', tagline: 'Terminación', descripcion: 'Sérum aceite en formato 30ml. Aporta brillo espejo, suavidad y nutrición sin peso. Controla el frizz.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Sérum Oil 60ml', tagline: 'Terminación', descripcion: 'Sérum aceite en formato 60ml. Aporta brillo espejo, suavidad y nutrición sin peso. Controla el frizz.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Acondicionador Sin Enjuague Liso 150ml', tagline: 'Terminación', descripcion: 'Acondicionador sin enjuague para cabellos lisos en formato 150ml. Suaviza, desenreda y protege la fibra manteniendo el liso.', precio: 0, linea: 'Terminación', tipo_cabello: ['Fino', 'Grueso'] },
  { nombre: 'Acondicionador Sin Enjuague Rulos 150ml', tagline: 'Terminación', descripcion: 'Acondicionador sin enjuague para rulos en formato 150ml. Define, hidrata y activa el rizo natural reduciendo el frizz.', precio: 0, linea: 'Terminación', tipo_cabello: ['Rizado'] },
  { nombre: 'Brillo Eslom Spray c/Siliconas 75ml', tagline: 'Terminación', descripcion: 'Spray de brillo con siliconas Eslom en formato 75ml. Aporta un acabado espejo instantáneo y sella la cutícula.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Dañado', 'Fino', 'Grueso'] },
  { nombre: 'Laca Eslom Spray Direccional Ecológico 200ml', tagline: 'Terminación', descripcion: 'Laca spray direccional ecológica Eslom en formato 200ml. Fijación fuerte y duradera sin gas dañino.', precio: 0, linea: 'Terminación', tipo_cabello: ['Fino', 'Grueso', 'Rizado'] },
  { nombre: 'Crema Modeladora Eslom c/Fijación 250ml', tagline: 'Terminación', descripcion: 'Crema modeladora con fijación Eslom en formato 250ml. Moldea y define el peinado con una fijación flexible y duradera.', precio: 0, linea: 'Terminación', tipo_cabello: ['Rizado', 'Grueso', 'Fino'] },
  { nombre: 'Crema Termo-Activa de Alisado Eslom 160ml', tagline: 'Terminación', descripcion: 'Crema termo-activa de alisado Eslom en formato 160ml. Activa con el calor de la plancha para alisar progresivamente.', precio: 0, linea: 'Terminación', tipo_cabello: ['Rizado', 'Grueso', 'Dañado'] },
  { nombre: 'Aceite Argán Eslom Oro Líquido 30ml', tagline: 'Terminación', descripcion: 'Aceite de argán Eslom Oro Líquido en formato 30ml. Nutrición ultraliviana con brillo espejo y suavidad de seda.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Aceite Argán Eslom Oro Líquido 60ml', tagline: 'Terminación', descripcion: 'Aceite de argán Eslom Oro Líquido en formato 60ml. Nutrición ultraliviana con brillo espejo y suavidad de seda.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Crema Lipoproteica Tonanol 150ml', tagline: 'Terminación', descripcion: 'Crema lipoproteica Tonanol en formato 150ml. Reconstruye y aporta suavidad y brillo al cabello dañado.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Pack 24 Ceras de Brillo 30g', tagline: 'Terminación', descripcion: 'Pack de 24 ceras de brillo en formato 30g cada una. Ideal para reventa o uso profesional en salón.', precio: 0, badge: 'Pack', linea: 'Terminación', tipo_cabello: ['Seco', 'Fino', 'Grueso'] },
  { nombre: 'Desenredante Bi-Fase Tonaleg 200ml', tagline: 'Terminación', descripcion: 'Desenredante bi-fase Tonaleg en formato 200ml. Fórmula en dos fases que desenreda sin esfuerzo, hidrata y aporta brillo.', precio: 0, linea: 'Terminación', tipo_cabello: ['Rizado', 'Dañado', 'Grueso'] },
  { nombre: 'Protector Térmico Tonaleg 200ml', tagline: 'Terminación', descripcion: 'Protector térmico Tonaleg en formato 200ml. Escuda la fibra capilar del daño del calor hasta 230°C.', precio: 0, linea: 'Terminación', tipo_cabello: ['Seco', 'Dañado', 'Teñido', 'Fino'] },
  // ── ANTI CAÍDA ────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Ortiga 300ml', tagline: 'Anti Caída', descripcion: 'Shampoo con ortiga en formato 300ml. Estimula el cuero cabelludo, fortalece la raíz y ayuda a reducir la caída del cabello.', precio: 0, linea: 'Anti Caída', tipo_cabello: ['Graso', 'Fino', 'Seco'] },
  { nombre: 'Loción de Ortiga Anti Caída 60ml', tagline: 'Anti Caída', descripcion: 'Loción capilar con ortiga en formato 60ml. Aplicación directa en el cuero cabelludo para estimular la circulación y fortalecer la raíz.', precio: 0, linea: 'Anti Caída', tipo_cabello: ['Fino', 'Graso', 'Seco'] },
  { nombre: 'Ampollas de Ortiga x12 15ml', tagline: 'Anti Caída', descripcion: 'Pack de 12 ampollas de ortiga de 15ml cada una. Tratamiento intensivo anti caída de aplicación directa en el cuero cabelludo.', precio: 0, badge: 'Pack', linea: 'Anti Caída', tipo_cabello: ['Fino', 'Seco', 'Dañado'] },
  // ── INTENSIVE REPAIR ──────────────────────────────────────────────────────
  { nombre: 'Shampoo Purity Intensive Repair NT4 300ml', tagline: 'Intensive Repair', descripcion: 'Shampoo Purity de la línea Intensive Repair NT4 en formato 300ml. Limpieza profunda que purifica el cuero cabelludo.', precio: 0, linea: 'Intensive Repair', tipo_cabello: ['Dañado', 'Teñido', 'Seco'] },
  { nombre: 'Máscara Argán y Macadamia Intensive Repair NT4 250ml', tagline: 'Intensive Repair', descripcion: 'Máscara con aceite de argán y macadamia NT4 en formato 250ml. Restaura en profundidad y aporta brillo duradero.', precio: 0, linea: 'Intensive Repair', tipo_cabello: ['Dañado', 'Seco', 'Teñido'] },
  { nombre: 'Shampoo Perfect Hidrat Intensive Repair NT4 300ml', tagline: 'Intensive Repair', descripcion: 'Shampoo hidratante Perfect Hidrat de la línea Intensive Repair NT4 en formato 300ml.', precio: 0, linea: 'Intensive Repair', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Acondicionador Perfect Hidrat Intensive Repair NT4 300ml', tagline: 'Intensive Repair', descripcion: 'Acondicionador hidratante Perfect Hidrat NT4 en formato 300ml. Sella la cutícula y aporta suavidad.', precio: 0, linea: 'Intensive Repair', tipo_cabello: ['Seco', 'Dañado', 'Fino'] },
  { nombre: 'Máscara Perfect Hidrat Intensive Repair NT4 250ml', tagline: 'Intensive Repair', descripcion: 'Máscara hidratante Perfect Hidrat NT4 en formato 250ml. Restaura la suavidad, el brillo y la elasticidad.', precio: 0, linea: 'Intensive Repair', tipo_cabello: ['Seco', 'Dañado'] },
  { nombre: 'Shampoo Nutrive Post Color Intensive Repair NT4 300ml', tagline: 'Intensive Repair', descripcion: 'Shampoo Nutrive Post Color NT4 en formato 300ml. Preserva la intensidad del color y aporta nutrición y brillo.', precio: 0, linea: 'Intensive Repair', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Acondicionador Nutrive Post Color Intensive Repair NT4 300ml', tagline: 'Intensive Repair', descripcion: 'Acondicionador Nutrive Post Color NT4 en formato 300ml. Sella la cutícula tras la coloración y prolonga la vida del color.', precio: 0, linea: 'Intensive Repair', tipo_cabello: ['Teñido', 'Dañado'] },
  // ── SILVER ────────────────────────────────────────────────────────────────
  { nombre: 'Shampoo Silver 300ml', tagline: 'Silver', descripcion: 'Shampoo matizador Silver en formato 300ml. Neutraliza los reflejos amarillos en cabellos blancos, plateados y decolorados.', precio: 0, linea: 'Silver', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Máscara Silver 300ml', tagline: 'Silver', descripcion: 'Máscara matizadora Silver en formato 300ml. Hidratación profunda con pigmentos violetas que eliminan los reflejos amarillos.', precio: 0, linea: 'Silver', tipo_cabello: ['Teñido', 'Dañado', 'Seco'] },
  { nombre: 'Shampoo Silver 980ml', tagline: 'Silver', descripcion: 'Shampoo matizador Silver en formato 980ml. Neutraliza los reflejos amarillos. Formato conveniente para uso intensivo.', precio: 0, linea: 'Silver', tipo_cabello: ['Teñido', 'Dañado'] },
  { nombre: 'Máscara Silver 980ml', tagline: 'Silver', descripcion: 'Máscara matizadora Silver en formato 980ml. Elimina los reflejos amarillos con pigmentos violetas de alta concentración.', precio: 0, linea: 'Silver', tipo_cabello: ['Teñido', 'Dañado', 'Seco'] },
  { nombre: 'Pack 24 Máscaras Silver 30g', tagline: 'Silver', descripcion: 'Pack de 24 máscaras matizadoras Silver de 30g cada una. Neutraliza los reflejos amarillos y aporta hidratación.', precio: 0, badge: 'Pack', linea: 'Silver', tipo_cabello: ['Teñido', 'Dañado', 'Seco'] },
]

async function seed() {
  const client = await db.connect()
  try {
    // Limpiar tabla y reinsertar todo
    await client.query('TRUNCATE TABLE productos RESTART IDENTITY')
    console.log('Tabla limpiada. Insertando productos...')
    for (const p of products) {
      await client.query(
        `INSERT INTO productos (nombre, tagline, descripcion, precio, badge, linea, tipo_cabello)
         VALUES ($1, $2, $3, $4, $5, $6, $7)`,
        [p.nombre, p.tagline, p.descripcion, p.precio, p.badge || null, p.linea, p.tipo_cabello]
      )
    }
    console.log(`✓ ${products.length} productos insertados`)
  } finally {
    client.release()
    await db.end()
  }
}

seed().catch(err => {
  console.error('Error en seed:', err.message)
  process.exit(1)
})
